// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVBfEfvQT0Rw3UK_8tdGWq6iIJBr3UJw',
    appId: '1:1094274305500:android:ba7a0ccee32fc7bbef9319',
    messagingSenderId: '1094274305500',
    projectId: 'fastfood-44fcd',
    storageBucket: 'fastfood-44fcd.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDcGOoK4p07hnji2duT4S5sNFmPPYHO4M',
    appId: '1:1094274305500:web:1a772c2eacc840ceef9319',
    messagingSenderId: '1094274305500',
    projectId: 'fastfood-44fcd',
    authDomain: 'fastfood-44fcd.firebaseapp.com',
    storageBucket: 'fastfood-44fcd.appspot.com',
    measurementId: 'G-5EXL7SM7QC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjjhUiroYa2Qfmg_ELXn6pk34duVJx-8',
    appId: '1:1094274305500:ios:a2db32c234701014ef9319',
    messagingSenderId: '1094274305500',
    projectId: 'fastfood-44fcd',
    storageBucket: 'fastfood-44fcd.appspot.com',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjjhUiroYa2Qfmg_ELXn6pk34duVJx-8',
    appId: '1:1094274305500:ios:a2db32c234701014ef9319',
    messagingSenderId: '1094274305500',
    projectId: 'fastfood-44fcd',
    storageBucket: 'fastfood-44fcd.appspot.com',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDcGOoK4p07hnji2duT4S5sNFmPPYHO4M',
    appId: '1:1094274305500:web:fa8cf6fded700978ef9319',
    messagingSenderId: '1094274305500',
    projectId: 'fastfood-44fcd',
    authDomain: 'fastfood-44fcd.firebaseapp.com',
    storageBucket: 'fastfood-44fcd.appspot.com',
    measurementId: 'G-EEPPW9QEW8',
  );

}